[workspace]
resolver = "2"
members = [
  "crates/emersia-daemon",
  "crates/emersia-cli",
  "crates/emersia-protocol",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/nicklin11/emersia"
rust-version = "1.86"

[profile.release]
lto = "thin"
strip = true
