name: Issue config
blank_issues_enabled: false
contact_links:
  - name: Emersia roadmap
    url: https://github.com/users/nicklin11/projects
    about: See what is planned, in progress, and up for grabs.
